---
- name: add host to AWS
  hosts: all
  collections:
  - amazon.aws
  tasks:
  - name: add host
    ec2_instance:
      name: "{{ instance_name }}"
      key_name: "{{ ssh_key_name }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ ec2_instance_type }}"
      security_group: "{{ security_group }}"
      network:
        assign_public_ip: "{{ assign_public_ip }}"
      image_id: "{{ image_id }}"
      access_key: "{{ access_key }}"
      secret_key: "{{ secret_key }}"
      state: present
      count: "{{ number_of_instances }}"
      region: "{{ aws_region }}"
    register: host_info
    when: inventory_hostname == play_hosts[0]

  - name: print hosts
    debug:
      var: host_info.instances[0].public_ip
    when: inventory_hostname == play_hosts[0]
