---
- name: ping hosts
  hosts: all
  tasks:
  - name: add host
    amazon.aws.ec2_instance:
      name: "{{ instance_name }}"
      key_name: "{{ ssh_key_name }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ ec2_instance_type }}"
      security_group: "{{ security_group }}"
      network:
        assign_public_ip: "{{ assign_public_ip }}"
      image_id: "{{ image_id }}"