---
- name: httpd installed
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: document root exist
  ansible.builtin.file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'
    setype: "httpd_sys_content_t"

- name: debug
  debug:
    var: "{{ ansible_network_interfaces.association.public_ip }}"

- name: custom index.html
  ansible.builtin.copy:
    dest: "/var/www/{{ http_host }}/index.html"
    content: |
                Custom Web Page {{ network_interfaces.public_ip }}

- name: setup Apache virtualhost
  ansible.builtin.template:
    src: "templates/httpd.conf.j2"
    dest: "/etc/httpd/conf.d/{{ http_conf }}"

- name: httpd service enabled
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: restarted

#- name: open firewall
#  ansible.posix.firewalld:
#    service: http
#    state: enabled
#    immediate: true
#    permanent: true
